GET  http://localhost:5000/users
###
GET  http://localhost:5000/products/1FTDzv

###
PATCH  http://localhost:5000/users/llmwhl
Content-Type: application/json

{
    "fullname": "M Iqbal",
    "age": 17,
    "username": "iqblfdrsyh",
    "no_handphone": "+6289671542333",
    "email": "iqblfrdsyh@gmail.com",
    "password": "iqbal123",
    "confirmPassword": "iqbal123",
    "gender": "Male"
}

###
DELETE  http://localhost:5000/users/llmwhl

### Register
POST http://localhost:5000/users
Content-Type: application/json

{
    "fullname": "Iyull",
    "age": 16,
    "username": "xvynlbl",
    "no_handphone": "+628967881313",
    "email": "iyull@gmail.com",
    "password": "yuli123",
    "confirmPassword": "yuli123",
    "gender": "Female"
}


### LOGIN
POST http://localhost:5000/login
Content-Type: application/json

{  
    "email": "iqbal123@gmail.com",
    "password": "iqbal123"  
}

### Cek Login
GET http://localhost:5000/islogin

### Logout
DELETE  http://localhost:5000/logout


###################################################################


### Product
POST http://localhost:5000/products
Content-Type: application/json

{
    "product_name": "Obat Asma",
    "product_image": "Product Image URL",
    "harga": 23000,
    "category_penyakit": "Asma",
    "categoryJenis_obat": "Obat Cair",
    "stock_product": 99,
    "deskripsi": "Product Description",
    "komposisi": "Product Composition",
    "dosis": "Product Dosage",
    "aturan_pakai": "Product Usage Guidelines",
    "kontra_indikasi": "Contraindications",
    "efek_samping": "Side Effects",
    "golongan_product": "Product Group",
    "expired_product": "2005-11-07 07:11:20"
}

### Category Obat
POST http://localhost:5000/categoryObat
Content-Type: application/json 

{
    "category_name" : "Obat Cair"
}

### Category Penyakit
POST http://localhost:5000/categoryPenyakit
Content-Type: application/json 

{
    "category_name" : "Asma"
}





